# Generated by Django 2.1.2 on 2018-11-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='office_hours',
            field=models.ManyToManyField(null=True, to='TaApp.OfficeHour'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
