# Generated by Django 2.1.2 on 2018-11-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.TextField(max_length=30)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaApp.ContactInfo')),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaApp.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(related_name='instructor_profile', to='TaApp.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='labs',
            field=models.ManyToManyField(to='TaApp.Lab'),
        ),
        migrations.AddField(
            model_name='course',
            name='tas',
            field=models.ManyToManyField(related_name='ta_profile', to='TaApp.User'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office_hours',
            field=models.ManyToManyField(to='TaApp.OfficeHour'),
        ),
    ]
