# Generated by Django 2.1.2 on 2018-12-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaApp', '0002_auto_20181115_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaApp.Account'),
        ),
    ]
