# Generated by Django 2.1.2 on 2018-11-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaApp', '0002_auto_20181114_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='office_hours',
        ),
        migrations.RemoveField(
            model_name='officehour',
            name='day',
        ),
        migrations.RemoveField(
            model_name='officehour',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='officehour',
            name='start_time',
        ),
        migrations.AddField(
            model_name='officehour',
            name='contact_info',
            field=models.ManyToManyField(to='TaApp.ContactInfo'),
        ),
        migrations.AddField(
            model_name='officehour',
            name='time',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
