# Generated by Django 2.1.2 on 2018-11-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaApp', '0003_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
