# Generated by Django 2.1.2 on 2018-12-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaApp', '0003_auto_20181214_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='ta',
        ),
        migrations.AddField(
            model_name='lab',
            name='ta',
            field=models.ManyToManyField(to='TaApp.Account'),
        ),
    ]
