# Generated by Django 2.1.2 on 2018-11-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaApp', '0003_auto_20181110_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_info',
        ),
    ]
