# Generated by Django 2.1.2 on 2018-11-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaApp', '0006_auto_20181111_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='office_hours',
            field=models.ManyToManyField(null=True, to='TaApp.OfficeHour'),
        ),
    ]
